spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/rentcardb?createDatabaseIfNotExist=true
    username: root
    password: admin123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
        